fix: Fixed missing proptypes import
WebpackError: ReferenceError: PropTypes is not defined
6:58:49 PM:
6:58:49 PM:   - home.js:32 Module.../../packages/bio/src/widget/home.js
6:58:49 PM:     opt/build/repo/packages/bio/src/widget/home.js:32:11
Signed-off-by: Sona Praneeth Akula <sonapraneeth.akula@gmail.com>