fix: Fixed an issue when option for mdx is false
Issue which is occurring when mdx is true in options
Error: Unable to find plugin "false". Perhaps you need to install its package?

Signed-off-by: Sona Praneeth Akula <sonapraneeth.akula@gmail.com>